### ISSUE TITLE
Culling impacts all numbers that end with a 0

### ISSUE THREAD

**Issue by Atulin** [Atulin/postcss-cull-units#1]
Even though tests pass with flying colours.

## Expected behaviour

```css
.foo {
  margin: 50px;
  padding: 0rem;
}
```
turns into
```css
.foo {
  margin: 50px;
  padding: 0;
}
```

## Actual behaviour

```css
.foo {
  margin: 50px;
  padding: 0rem;
}
```
turns into
```css
.foo {
  margin: 50;
  padding: 0;
}
```
